language: ruby
rvm:
  - 2.4.5
addons:
  postgresql: 9.6
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database notesy_test;' -U postgres
dist: trusty
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
services:
  - redis-server
  